/*
 Highmaps JS v10.0.0 (2022-03-07)

 (c) 2009-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/heatmap",["highcharts"],function(x){c(x);c.Highcharts=x;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function x(c,h,z,n){c.hasOwnProperty(h)||(c[h]=n.apply(null,z),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:h,module:c[h]}})))}c=c?c._modules:{};x(c,
"Core/Axis/Color/ColorAxisComposition.js",[c["Core/Color/Color.js"],c["Core/Utilities.js"]],function(c,h){var r=c.parse,n=h.addEvent,y=h.extend,t=h.merge,A=h.pick,B=h.splat,m;(function(f){function c(){var b=this,a=this.options;this.colorAxis=[];a.colorAxis&&(a.colorAxis=B(a.colorAxis),a.colorAxis.forEach(function(a,d){a.index=d;new k(b,a)}))}function h(a){var b=this,d=function(d){d=a.allItems.indexOf(d);-1!==d&&(b.destroyItem(a.allItems[d]),a.allItems.splice(d,1))},e=[],p,k;(this.chart.colorAxis||
[]).forEach(function(a){(p=a.options)&&p.showInLegend&&(p.dataClasses&&p.visible?e=e.concat(a.getDataClassLegendSymbols()):p.visible&&e.push(a),a.series.forEach(function(a){if(!a.options.showInLegend||p.dataClasses)"point"===a.options.legendType?a.points.forEach(function(a){d(a)}):d(a)}))});for(k=e.length;k--;)a.allItems.unshift(e[k])}function m(a){a.visible&&a.item.legendColor&&a.item.legendSymbol.attr({fill:a.item.legendColor})}function u(){var a=this.chart.colorAxis;a&&a.forEach(function(a,b,d){a.update({},
d)})}function w(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()}function q(){var a=this.axisTypes;a?-1===a.indexOf("colorAxis")&&a.push("colorAxis"):this.axisTypes=["colorAxis"]}function E(a){var b=this,d=a?"show":"hide";b.visible=b.options.visible=!!a;["graphic","dataLabel"].forEach(function(a){if(b[a])b[a][d]()});this.series.buildKDTree()}function g(){var a=this,b=this.options.nullColor,d=this.colorAxis,e=this.colorKey;(this.data.length?this.data:
this.points).forEach(function(k){var l=k.getNestedProperty(e);(l=k.options.color||(k.isNull||null===k.value?b:d&&"undefined"!==typeof l?d.toColor(l,k):k.color||a.color))&&k.color!==l&&(k.color=l,"point"===a.options.legendType&&k.legendItem&&a.chart.legend.colorizeItem(k,k.visible))})}function e(a){var b=a.prototype.createAxis;a.prototype.createAxis=function(a,d){if("colorAxis"!==a)return b.apply(this,arguments);var e=new k(this,t(d.axis,{index:this[a].length,isX:!1}));this.isDirtyLegend=!0;this.axes.forEach(function(a){a.series=
[]});this.series.forEach(function(a){a.bindAxes();a.isDirtyData=!0});A(d.redraw,!0)&&this.redraw(d.animation);return e}}function d(){this.elem.attr("fill",r(this.start).tweenTo(r(this.end),this.pos),void 0,!0)}function b(){this.elem.attr("stroke",r(this.start).tweenTo(r(this.end),this.pos),void 0,!0)}var a=[],k;f.compose=function(p,l,C,f,v){k||(k=p);-1===a.indexOf(l)&&(a.push(l),p=l.prototype,p.collectionsWithUpdate.push("colorAxis"),p.collectionsWithInit.colorAxis=[p.addColorAxis],n(l,"afterGetAxes",
c),e(l));-1===a.indexOf(C)&&(a.push(C),l=C.prototype,l.fillSetter=d,l.strokeSetter=b);-1===a.indexOf(f)&&(a.push(f),n(f,"afterGetAllItems",h),n(f,"afterColorizeItem",m),n(f,"afterUpdate",u));-1===a.indexOf(v)&&(a.push(v),y(v.prototype,{optionalAxis:"colorAxis",translateColors:g}),y(v.prototype.pointClass.prototype,{setVisible:E}),n(v,"afterTranslate",w),n(v,"bindAxes",q))};f.pointSetVisible=E})(m||(m={}));return m});x(c,"Core/Axis/Color/ColorAxisDefaults.js",[],function(){return{lineWidth:0,minPadding:0,
maxPadding:0,gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},width:.01,color:"#999999"},labels:{overflow:"justify",rotation:0},minColor:"#e6ebf5",maxColor:"#003399",tickLength:5,showInLegend:!0}});x(c,"Core/Axis/Color/ColorAxis.js",[c["Core/Axis/Axis.js"],c["Core/Color/Color.js"],c["Core/Axis/Color/ColorAxisComposition.js"],c["Core/Axis/Color/ColorAxisDefaults.js"],c["Core/Globals.js"],c["Core/Legend/LegendSymbol.js"],c["Core/Series/SeriesRegistry.js"],
c["Core/Utilities.js"]],function(c,h,z,n,y,t,A,B){var m=this&&this.__extends||function(){var f=function(g,e){f=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(d,b){d.__proto__=b}||function(d,b){for(var a in b)b.hasOwnProperty(a)&&(d[a]=b[a])};return f(g,e)};return function(g,e){function d(){this.constructor=g}f(g,e);g.prototype=null===e?Object.create(e):(d.prototype=e.prototype,new d)}}(),f=h.parse,v=y.noop,r=A.series,D=B.extend,u=B.isNumber,w=B.merge,q=B.pick;h=function(c){function g(e,
d){var b=c.call(this,e,d)||this;b.beforePadding=!1;b.chart=void 0;b.coll="colorAxis";b.dataClasses=void 0;b.legendItem=void 0;b.legendItems=void 0;b.name="";b.options=void 0;b.stops=void 0;b.visible=!0;b.init(e,d);return b}m(g,c);g.compose=function(e,d,b,a){z.compose(g,e,d,b,a)};g.prototype.init=function(e,d){var b=e.options.legend||{},a=d.layout?"vertical"!==d.layout:"vertical"!==b.layout,k=d.visible;b=w(g.defaultColorAxisOptions,d,{showEmpty:!1,title:null,visible:b.enabled&&!1!==k});this.coll="colorAxis";
this.side=d.side||a?2:1;this.reversed=d.reversed||!a;this.opposite=!a;c.prototype.init.call(this,e,b);this.userOptions.visible=k;d.dataClasses&&this.initDataClasses(d);this.initStops();this.horiz=a;this.zoomEnabled=!1};g.prototype.initDataClasses=function(e){var d=this.chart,b=this.options,a=e.dataClasses.length,k,c=0,l=d.options.chart.colorCount;this.dataClasses=k=[];this.legendItems=[];(e.dataClasses||[]).forEach(function(e,g){e=w(e);k.push(e);if(d.styledMode||!e.color)"category"===b.dataClassColor?
(d.styledMode||(g=d.options.colors,l=g.length,e.color=g[c]),e.colorIndex=c,c++,c===l&&(c=0)):e.color=f(b.minColor).tweenTo(f(b.maxColor),2>a?.5:g/(a-1))})};g.prototype.hasData=function(){return!!(this.tickPositions||[]).length};g.prototype.setTickPositions=function(){if(!this.dataClasses)return c.prototype.setTickPositions.call(this)};g.prototype.initStops=function(){this.stops=this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(e){e.color=f(e[1])})};
g.prototype.setOptions=function(e){c.prototype.setOptions.call(this,e);this.options.crosshair=this.options.marker};g.prototype.setAxisSize=function(){var e=this.legendSymbol,d=this.chart,b=d.options.legend||{},a,k;e?(this.left=b=e.attr("x"),this.top=a=e.attr("y"),this.width=k=e.attr("width"),this.height=e=e.attr("height"),this.right=d.chartWidth-b-k,this.bottom=d.chartHeight-a-e,this.len=this.horiz?k:e,this.pos=this.horiz?b:a):this.len=(this.horiz?b.symbolWidth:b.symbolHeight)||g.defaultLegendLength};
g.prototype.normalizedValue=function(e){this.logarithmic&&(e=this.logarithmic.log2lin(e));return 1-(this.max-e)/(this.max-this.min||1)};g.prototype.toColor=function(e,d){var b=this.dataClasses,a=this.stops,k;if(b)for(k=b.length;k--;){var c=b[k];var l=c.from;a=c.to;if(("undefined"===typeof l||e>=l)&&("undefined"===typeof a||e<=a)){var g=c.color;d&&(d.dataClass=k,d.colorIndex=c.colorIndex);break}}else{e=this.normalizedValue(e);for(k=a.length;k--&&!(e>a[k][0]););l=a[k]||a[k+1];a=a[k+1]||l;e=1-(a[0]-
e)/(a[0]-l[0]||1);g=l.color.tweenTo(a.color,e)}return g};g.prototype.getOffset=function(){var e=this.legendGroup,d=this.chart.axisOffset[this.side];if(e){this.axisParent=e;c.prototype.getOffset.call(this);var b=this.chart.legend;b.allItems.forEach(function(a){a instanceof g&&a.drawLegendSymbol(b,a)});b.render();this.chart.getMargins(!0);this.added||(this.added=!0,this.labelLeft=0,this.labelRight=this.width);this.chart.axisOffset[this.side]=d}};g.prototype.setLegendColor=function(){var e=this.reversed,
d=e?1:0;e=e?0:1;d=this.horiz?[d,0,e,0]:[0,e,0,d];this.legendColor={linearGradient:{x1:d[0],y1:d[1],x2:d[2],y2:d[3]},stops:this.stops}};g.prototype.drawLegendSymbol=function(e,d){var b=e.padding,a=e.options,k=this.horiz,c=q(a.symbolWidth,k?g.defaultLegendLength:12),l=q(a.symbolHeight,k?12:g.defaultLegendLength),f=q(a.labelPadding,k?16:30);a=q(a.itemDistance,10);this.setLegendColor();d.legendSymbol||(d.legendSymbol=this.chart.renderer.rect(0,e.baseline-11,c,l).attr({zIndex:1}).add(d.legendGroup));this.legendItemWidth=
c+b+(k?a:this.options.labels.x+this.maxLabelLength);this.legendItemHeight=l+b+(k?f:0)};g.prototype.setState=function(e){this.series.forEach(function(d){d.setState(e)})};g.prototype.setVisible=function(){};g.prototype.getSeriesExtremes=function(){var e=this.series,d=e.length,b;this.dataMin=Infinity;for(this.dataMax=-Infinity;d--;){var a=e[d];var k=a.colorKey=q(a.options.colorKey,a.colorKey,a.pointValKey,a.zoneAxis,"y");var c=a.pointArrayMap;var l=a[k+"Min"]&&a[k+"Max"];if(a[k+"Data"])var g=a[k+"Data"];
else if(c){g=[];c=c.indexOf(k);var f=a.yData;if(0<=c&&f)for(b=0;b<f.length;b++)g.push(q(f[b][c],f[b]))}else g=a.yData;l?(a.minColorValue=a[k+"Min"],a.maxColorValue=a[k+"Max"]):(g=r.prototype.getExtremes.call(a,g),a.minColorValue=g.dataMin,a.maxColorValue=g.dataMax);"undefined"!==typeof a.minColorValue&&(this.dataMin=Math.min(this.dataMin,a.minColorValue),this.dataMax=Math.max(this.dataMax,a.maxColorValue));l||r.prototype.applyExtremes.call(a)}};g.prototype.drawCrosshair=function(e,d){var b=d&&d.plotX,
a=d&&d.plotY,k=this.pos,g=this.len;if(d){var f=this.toPixels(d.getNestedProperty(d.series.colorKey));f<k?f=k-2:f>k+g&&(f=k+g+2);d.plotX=f;d.plotY=this.len-f;c.prototype.drawCrosshair.call(this,e,d);d.plotX=b;d.plotY=a;this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),this.cross.addedToColorAxis=!0,this.chart.styledMode||"object"!==typeof this.crosshair||this.cross.attr({fill:this.crosshair.color}))}};g.prototype.getPlotLinePath=
function(e){var d=this.left,b=e.translatedValue,a=this.top;return u(b)?this.horiz?[["M",b-4,a-6],["L",b+4,a-6],["L",b,a],["Z"]]:[["M",d,b],["L",d-6,b+6],["L",d-6,b-6],["Z"]]:c.prototype.getPlotLinePath.call(this,e)};g.prototype.update=function(e,d){var b=this.chart.legend;this.series.forEach(function(a){a.isDirtyData=!0});(e.dataClasses&&b.allItems||this.dataClasses)&&this.destroyItems();c.prototype.update.call(this,e,d);this.legendItem&&(this.setLegendColor(),b.colorizeItem(this,!0))};g.prototype.destroyItems=
function(){var e=this.chart;this.legendItem?e.legend.destroyItem(this):this.legendItems&&this.legendItems.forEach(function(d){e.legend.destroyItem(d)});e.isDirtyLegend=!0};g.prototype.destroy=function(){this.chart.isDirtyLegend=!0;this.destroyItems();c.prototype.destroy.apply(this,[].slice.call(arguments))};g.prototype.remove=function(e){this.destroyItems();c.prototype.remove.call(this,e)};g.prototype.getDataClassLegendSymbols=function(){var e=this,d=e.chart,b=e.legendItems,a=d.options.legend,c=a.valueDecimals,
g=a.valueSuffix||"",f;b.length||e.dataClasses.forEach(function(a,k){var l=a.from,h=a.to,C=d.numberFormatter,p=!0;f="";"undefined"===typeof l?f="< ":"undefined"===typeof h&&(f="> ");"undefined"!==typeof l&&(f+=C(l,c)+g);"undefined"!==typeof l&&"undefined"!==typeof h&&(f+=" - ");"undefined"!==typeof h&&(f+=C(h,c)+g);b.push(D({chart:d,name:f,options:{},drawLegendSymbol:t.drawRectangle,visible:!0,setState:v,isDataClass:!0,setVisible:function(){p=e.visible=!p;e.series.forEach(function(a){a.points.forEach(function(a){a.dataClass===
k&&a.setVisible(p)})});d.legend.colorizeItem(this,p)}},a))});return b};g.defaultColorAxisOptions=n;g.defaultLegendLength=200;g.keepProps=["legendGroup","legendItemHeight","legendItemWidth","legendItem","legendSymbol"];return g}(c);Array.prototype.push.apply(c.keepProps,h.keepProps);"";return h});x(c,"Series/ColorMapMixin.js",[c["Core/Globals.js"],c["Core/Series/Point.js"],c["Core/Utilities.js"]],function(c,h,z){var r=c.noop;c=c.seriesTypes;var y=z.defined;z=z.addEvent;z(h,"afterSetState",function(c){this.moveToTopOnHover&&
this.graphic&&this.graphic.attr({zIndex:c&&"hover"===c.state?1:0})});return{PointMixin:{dataLabelOnNull:!0,moveToTopOnHover:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value}},SeriesMixin:{pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:r,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:c.column.prototype.pointAttribs,colorAttribs:function(c){var h={};!y(c.color)||
c.state&&"normal"!==c.state||(h[this.colorProp||"fill"]=c.color);return h}}}});x(c,"Series/Heatmap/HeatmapPoint.js",[c["Core/Series/SeriesRegistry.js"],c["Core/Utilities.js"]],function(c,h){var r=this&&this.__extends||function(){var c=function(h,f){c=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,f){c.__proto__=f}||function(c,f){for(var h in f)f.hasOwnProperty(h)&&(c[h]=f[h])};return c(h,f)};return function(h,f){function v(){this.constructor=h}c(h,f);h.prototype=null===f?Object.create(f):
(v.prototype=f.prototype,new v)}}(),n=h.clamp,y=h.defined,t=h.extend,A=h.pick;c=function(c){function h(){var f=null!==c&&c.apply(this,arguments)||this;f.options=void 0;f.series=void 0;f.value=void 0;f.x=void 0;f.y=void 0;return f}r(h,c);h.prototype.applyOptions=function(f,h){f=c.prototype.applyOptions.call(this,f,h);f.formatPrefix=f.isNull||null===f.value?"null":"point";return f};h.prototype.getCellAttributes=function(){var c=this.series,h=c.options,r=(h.colsize||1)/2,m=(h.rowsize||1)/2,u=c.xAxis,
w=c.yAxis,q=this.options.marker||c.options.marker;c=c.pointPlacementToXValue();var t=A(this.pointPadding,h.pointPadding,0),g={x1:n(Math.round(u.len-(u.translate(this.x-r,!1,!0,!1,!0,-c)||0)),-u.len,2*u.len),x2:n(Math.round(u.len-(u.translate(this.x+r,!1,!0,!1,!0,-c)||0)),-u.len,2*u.len),y1:n(Math.round(w.translate(this.y-m,!1,!0,!1,!0)||0),-w.len,2*w.len),y2:n(Math.round(w.translate(this.y+m,!1,!0,!1,!0)||0),-w.len,2*w.len)};[["width","x"],["height","y"]].forEach(function(c){var d=c[0];c=c[1];var b=
c+"1",a=c+"2",e=Math.abs(g[b]-g[a]),f=q&&q.lineWidth||0,h=Math.abs(g[b]+g[a])/2;d=q&&q[d];y(d)&&d<e&&(d=d/2+f/2,g[b]=h-d,g[a]=h+d);t&&("y"===c&&(b=a,a=c+"1"),g[b]+=t,g[a]-=t)});return g};h.prototype.haloPath=function(c){if(!c)return[];var f=this.shapeArgs;return["M",f.x-c,f.y-c,"L",f.x-c,f.y+f.height+c,f.x+f.width+c,f.y+f.height+c,f.x+f.width+c,f.y-c,"Z"]};h.prototype.isValid=function(){return Infinity!==this.value&&-Infinity!==this.value};return h}(c.seriesTypes.scatter.prototype.pointClass);t(c.prototype,
{dataLabelOnNull:!0,moveToTopOnHover:!0,ttBelow:!1});return c});x(c,"Series/Heatmap/HeatmapSeries.js",[c["Core/Color/Color.js"],c["Series/ColorMapMixin.js"],c["Series/Heatmap/HeatmapPoint.js"],c["Core/Legend/LegendSymbol.js"],c["Core/Series/SeriesRegistry.js"],c["Core/Renderer/SVG/SVGRenderer.js"],c["Core/Utilities.js"]],function(c,h,x,n,y,t,A){var r=this&&this.__extends||function(){var c=function(d,b){c=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,
b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return c(d,b)};return function(d,b){function a(){this.constructor=d}c(d,b);d.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)}}(),m=y.series,f=y.seriesTypes,v=f.column,z=f.scatter,D=t.prototype.symbols,u=A.extend,w=A.fireEvent,q=A.isNumber,E=A.merge,g=A.pick;t=function(e){function d(){var b=null!==e&&e.apply(this,arguments)||this;b.colorAxis=void 0;b.data=void 0;b.options=void 0;b.points=void 0;b.valueMax=NaN;b.valueMin=NaN;return b}
r(d,e);d.prototype.drawPoints=function(){var b=this;if((this.options.marker||{}).enabled||this._hasPointMarkers)m.prototype.drawPoints.call(this),this.points.forEach(function(a){a.graphic&&(a.graphic[b.chart.styledMode?"css":"animate"](b.colorAttribs(a)),b.options.borderRadius&&a.graphic.attr({r:b.options.borderRadius}),(a.shapeArgs||{}).r=b.options.borderRadius,(a.shapeArgs||{}).d=a.graphic.pathArray,null===a.value&&a.graphic.addClass("highcharts-null-point"))})};d.prototype.getExtremes=function(){var b=
m.prototype.getExtremes.call(this,this.valueData),a=b.dataMin;b=b.dataMax;q(a)&&(this.valueMin=a);q(b)&&(this.valueMax=b);return m.prototype.getExtremes.call(this)};d.prototype.getValidPoints=function(b,a){return m.prototype.getValidPoints.call(this,b,a,!0)};d.prototype.hasData=function(){return!!this.processedXData.length};d.prototype.init=function(){m.prototype.init.apply(this,arguments);var b=this.options;b.pointRange=g(b.pointRange,b.colsize||1);this.yAxis.axisPointRange=b.rowsize||1;D.ellipse=
D.circle};d.prototype.markerAttribs=function(b,a){var c=b.marker||{},d=this.options.marker||{},e=b.shapeArgs||{},f={};if(b.hasImage)return{x:b.plotX,y:b.plotY};if(a){var g=d.states[a]||{};var h=c.states&&c.states[a]||{};[["width","x"],["height","y"]].forEach(function(a){f[a[0]]=(h[a[0]]||g[a[0]]||e[a[0]])+(h[a[0]+"Plus"]||g[a[0]+"Plus"]||0);f[a[1]]=e[a[1]]+(e[a[0]]-f[a[0]])/2})}return a?f:e};d.prototype.pointAttribs=function(b,a){var d=m.prototype.pointAttribs.call(this,b,a),e=this.options||{},f=
this.chart.options.plotOptions||{},g=f.series||{},h=f.heatmap||{};f=b&&b.options.borderColor||e.borderColor||h.borderColor||g.borderColor;g=b&&b.options.borderWidth||e.borderWidth||h.borderWidth||g.borderWidth||d["stroke-width"];d.stroke=b&&b.marker&&b.marker.lineColor||e.marker&&e.marker.lineColor||f||this.color;d["stroke-width"]=g;a&&(b=E(e.states[a],e.marker&&e.marker.states[a],b&&b.options.states&&b.options.states[a]||{}),a=b.brightness,d.fill=b.color||c.parse(d.fill).brighten(a||0).get(),d.stroke=
b.lineColor);return d};d.prototype.setClip=function(b){var a=this.chart;m.prototype.setClip.apply(this,arguments);(!1!==this.options.clip||b)&&this.markerGroup.clip((b||this.clipBox)&&this.sharedClipKey?a.sharedClips[this.sharedClipKey]:a.clipRect)};d.prototype.translate=function(){var b=this.options,a=b.marker&&b.marker.symbol||"rect",c=D[a]?a:"rect",d=-1!==["circle","square"].indexOf(c);this.generatePoints();this.points.forEach(function(b){var e=b.getCellAttributes(),f={};f.x=Math.min(e.x1,e.x2);
f.y=Math.min(e.y1,e.y2);f.width=Math.max(Math.abs(e.x2-e.x1),0);f.height=Math.max(Math.abs(e.y2-e.y1),0);var g=b.hasImage=0===(b.marker&&b.marker.symbol||a||"").indexOf("url");if(d){var h=Math.abs(f.width-f.height);f.x=Math.min(e.x1,e.x2)+(f.width<f.height?0:h/2);f.y=Math.min(e.y1,e.y2)+(f.width<f.height?h/2:0);f.width=f.height=Math.min(f.width,f.height)}h={plotX:(e.x1+e.x2)/2,plotY:(e.y1+e.y2)/2,clientX:(e.x1+e.x2)/2,shapeType:"path",shapeArgs:E(!0,f,{d:D[c](f.x,f.y,f.width,f.height)})};g&&(b.marker=
{width:f.width,height:f.height});u(b,h)});w(this,"afterTranslate")};d.defaultOptions=E(z.defaultOptions,{animation:!1,borderRadius:0,borderWidth:0,nullColor:"#f7f7f7",dataLabels:{formatter:function(){var b=this.series.chart.numberFormatter,a=this.point.value;return q(a)?b(a,-1):""},inside:!0,verticalAlign:"middle",crop:!1,overflow:!1,padding:0},marker:{symbol:"rect",radius:0,lineColor:void 0,states:{hover:{lineWidthPlus:0},select:{}}},clip:!0,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},
states:{hover:{halo:!1,brightness:.2}}});return d}(z);u(t.prototype,{alignDataLabel:v.prototype.alignDataLabel,axisTypes:h.SeriesMixin.axisTypes,colorAttribs:h.SeriesMixin.colorAttribs,colorKey:h.SeriesMixin.colorKey,directTouch:!0,drawLegendSymbol:n.drawRectangle,getExtremesFromAll:!0,getSymbol:m.prototype.getSymbol,parallelArrays:h.SeriesMixin.parallelArrays,pointArrayMap:["y","value"],pointClass:x,trackerGroups:h.SeriesMixin.trackerGroups});y.registerSeriesType("heatmap",t);"";"";return t});x(c,
"masters/modules/heatmap.src.js",[c["Core/Globals.js"],c["Core/Axis/Color/ColorAxis.js"]],function(c,h){c.ColorAxis=h;h.compose(c.Chart,c.Fx,c.Legend,c.Series)})});
//# sourceMappingURL=heatmap.js.map