// Generated by CoffeeScript 1.7.1
(function() {
  var Authorization, Evie, base64, clone, clone_actions, include, overload, querystring, request, resolve_url, resource, type, _ref,
    __slice = [].slice;

  querystring = require("querystring");

  resolve_url = (require("url")).resolve;

  _ref = require("fairmont"), include = _ref.include, clone = _ref.clone, type = _ref.type, base64 = _ref.base64;

  overload = require("typely").overload;

  Evie = require("evie");

  request = require("./request").request;

  Authorization = {
    basic: function(_arg) {
      var password, username;
      username = _arg.username, password = _arg.password;
      return "Basic " + base64("" + username + ":" + password);
    }
  };

  clone_actions = function(description) {
    var definition, method, _description;
    _description = {};
    for (method in description) {
      definition = description[method];
      if (type(definition) !== "function") {
        _description[method] = definition;
      }
    }
    return _description;
  };

  resource = overload(function(match) {
    match("string", function(url) {
      return resource({
        url: url
      });
    });
    match("string", "object", function(url, description) {
      return resource({
        url: url,
        description: description
      });
    });
    return match("object", function(_arg) {
      var definition, description, events, from_parameters, from_path, make_request, method, url, _resource;
      url = _arg.url, events = _arg.events, description = _arg.description;
      from_path = function(path, _description) {
        if (_description == null) {
          _description = clone_actions(description);
        }
        return resource({
          url: resolve_url(url, path),
          events: events.source(),
          description: _description
        });
      };
      from_parameters = (function() {
        var template;
        template = (require("url-template")).parse(url);
        return function(parameters, _description) {
          if (_description == null) {
            _description = description;
          }
          return resource({
            url: template.expand(parameters),
            events: events.source(),
            description: _description
          });
        };
      })();
      make_request = function(definition) {
        var fn;
        if (definition.events == null) {
          definition.events = events;
        }
        if (definition.url == null) {
          definition.url = url;
        }
        if (definition.headers == null) {
          definition.headers = {};
        }
        fn = function() {
          return request.apply(null, [definition].concat(__slice.call(arguments)));
        };
        fn.invoke = function() {
          return fn.apply(null, arguments);
        };
        include(fn, {
          authorize: function(credentials) {
            var authorization, scheme, transform, _definition;
            scheme = Object.keys(credentials)[0];
            transform = Authorization[scheme];
            authorization = transform(credentials[scheme]);
            _definition = clone(definition);
            _definition.headers.authorization = authorization;
            return make_request(_definition);
          }
        });
        return fn;
      };
      if (events == null) {
        events = new Evie;
      }
      _resource = overload(function(match) {
        match("string", function(path) {
          return from_path(path);
        });
        match("string", "object", function(path, description) {
          return from_path(path, description);
        });
        match("object", function(parameters) {
          return from_parameters(parameters);
        });
        return match("object", "object", function(parameters, description) {
          return from_parameters(parameters, description);
        });
      });
      _resource.on = function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        events.on.apply(events, args);
        return _resource;
      };
      for (method in description) {
        definition = description[method];
        _resource[method] = (function() {
          switch (type(definition)) {
            case "object":
              return make_request(clone(definition));
            case "function":
              return definition(_resource);
          }
        })();
      }
      return _resource;
    });
  });

  module.exports = {
    resource: resource
  };

}).call(this);
