define(
//begin v1.x content
{
	"dateFormatItem-yMMMM": "MMMM G y",
	"field-thu-narrow-relative+0": "พฤหัสนี้",
	"field-thu-narrow-relative+1": "พฤหัสหน้า",
	"field-sun-narrow-relative+0": "วันอาทิตย์นี้",
	"field-sun-narrow-relative+1": "วันอาทิตย์หน้า",
	"months-format-wide": [
		"มกราคม",
		"กุมภาพันธ์",
		"มีนาคม",
		"เมษายน",
		"พฤษภาคม",
		"มิถุนายน",
		"กรกฎาคม",
		"สิงหาคม",
		"กันยายน",
		"ตุลาคม",
		"พฤศจิกายน",
		"ธันวาคม"
	],
	"dayPeriods-standAlone-abbr-pm": "หลังเที่ยง",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-fri-narrow-relative+0": "ศุกร์นี้",
	"field-fri-narrow-relative+1": "ศุกร์หน้า",
	"eraNarrow": [
		"ก่อน ค.ศ.",
		"ก.ส.ศ.",
		"ค.ศ.",
		"ส.ศ."
	],
	"dateFormatItem-Hmv": "HH:mm v",
	"dateFormatItem-hmsv": "h:mm:ss a v",
	"dateFormatItem-yMMMd": "d MMM y",
	"dayPeriods-format-abbr-night1": "กลางคืน",
	"dayPeriods-format-narrow-evening1": "เย็น",
	"days-standAlone-narrow": [
		"อา",
		"จ",
		"อ",
		"พ",
		"พฤ",
		"ศ",
		"ส"
	],
	"dayPeriods-format-narrow-evening2": "ค่ำ",
	"days-standAlone-wide": [
		"วันอาทิตย์",
		"วันจันทร์",
		"วันอังคาร",
		"วันพุธ",
		"วันพฤหัสบดี",
		"วันศุกร์",
		"วันเสาร์"
	],
	"dayPeriods-format-abbr-afternoon1": "ในตอนบ่าย",
	"dayPeriods-format-wide-evening1": "ในตอนเย็น",
	"dayPeriods-format-abbr-afternoon2": "บ่าย",
	"dayPeriods-format-wide-evening2": "ค่ำ",
	"dateFormatItem-Ehm": "E h:mm a",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-wed-narrow-relative+-1": "พุธที่แล้ว",
	"dayPeriods-standAlone-wide-evening1": "ในตอนเย็น",
	"dayPeriods-standAlone-wide-evening2": "ค่ำ",
	"days-format-wide": [
		"วันอาทิตย์",
		"วันจันทร์",
		"วันอังคาร",
		"วันพุธ",
		"วันพฤหัสบดี",
		"วันศุกร์",
		"วันเสาร์"
	],
	"field-month-short-relative+0": "เดือนนี้",
	"field-month-short-relative+1": "เดือนหน้า",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"dayPeriods-standAlone-narrow-evening1": "เย็น",
	"dayPeriods-standAlone-narrow-evening2": "ค่ำ",
	"dayPeriods-standAlone-abbr-afternoon1": "ในตอนบ่าย",
	"dayPeriods-standAlone-abbr-afternoon2": "บ่าย",
	"field-thu-relative+0": "พฤหัสนี้",
	"dayPeriods-standAlone-abbr-night1": "กลางคืน",
	"field-thu-relative+1": "พฤหัสหน้า",
	"dayPeriods-format-wide-am": "ก่อนเที่ยง",
	"field-fri-relative+0": "ศุกร์นี้",
	"field-fri-relative+1": "ศุกร์หน้า",
	"dateFormatItem-yMd": "d/M/y",
	"field-thu-narrow-relative+-1": "พฤหัสที่แล้ว",
	"field-quarter-relative+0": "ไตรมาสนี้",
	"field-quarter-relative+1": "ไตรมาสหน้า",
	"field-sun-short-relative+0": "วันอาทิตย์นี้",
	"timeFormat-short": "HH:mm",
	"field-sun-short-relative+1": "วันอาทิตย์หน้า",
	"dateFormatItem-hms": "h:mm:ss a",
	"dayPeriods-format-narrow-afternoon1": "เที่ยง",
	"dateFormatItem-Md": "d/M",
	"dayPeriods-format-narrow-afternoon2": "บ่าย",
	"dateFormatItem-Hmsv": "HH:mm:ss v",
	"dateFormatItem-hmv": "h:mm น. a v",
	"field-week-narrow": "สัปดาห์",
	"dateFormatItem-GyMMMEEEEd": "EEEEที่ d MMM G y",
	"field-hour-relative+0": "ชั่วโมงนี้",
	"field-day-relative+-1": "เมื่อวาน",
	"field-day-relative+-2": "เมื่อวานซืน",
	"field-mon-narrow-relative+-1": "จันทร์ที่แล้ว",
	"field-minute-narrow": "นาที",
	"dateFormatItem-MMMMEd": "E d MMMM",
	"field-thu-short-relative+0": "พฤหัสนี้",
	"field-mon-relative+0": "จันทร์นี้",
	"field-thu-short-relative+1": "พฤหัสหน้า",
	"field-mon-relative+1": "จันทร์หน้า",
	"field-day-narrow-relative+0": "วันนี้",
	"field-era-short": "สมัย",
	"field-day-narrow-relative+1": "พรุ่งนี้",
	"field-day-narrow-relative+2": "มะรืนนี้",
	"field-sat-narrow-relative+0": "เสาร์นี้",
	"timeFormat-long": "H นาฬิกา mm นาที ss วินาที z",
	"field-sat-narrow-relative+1": "เสาร์หน้า",
	"field-week-narrow-relative+0": "สัปดาห์นี้",
	"field-week-narrow-relative+1": "สัปดาห์หน้า",
	"field-wed-narrow-relative+0": "พุธนี้",
	"field-wed-narrow-relative+1": "พุธหน้า",
	"field-month": "เดือน",
	"months-standAlone-wide": [
		"มกราคม",
		"กุมภาพันธ์",
		"มีนาคม",
		"เมษายน",
		"พฤษภาคม",
		"มิถุนายน",
		"กรกฎาคม",
		"สิงหาคม",
		"กันยายน",
		"ตุลาคม",
		"พฤศจิกายน",
		"ธันวาคม"
	],
	"field-weekday-narrow": "วันของสัปดาห์",
	"dayPeriods-standAlone-narrow-afternoon1": "ช่วงเที่ยง",
	"dayPeriods-standAlone-narrow-afternoon2": "บ่าย",
	"field-year-relative+0": "ปีนี้",
	"field-year-relative+1": "ปีหน้า",
	"dayPeriods-format-abbr-evening1": "ในตอนเย็น",
	"dayPeriods-format-abbr-evening2": "ค่ำ",
	"dayPeriods-format-abbr-noon": "เที่ยง",
	"dayPeriods-format-narrow-midnight": "เที่ยงคืน",
	"dayPeriods-format-wide-midnight": "เที่ยงคืน",
	"field-tue-relative+0": "อังคารนี้",
	"field-tue-relative+1": "อังคารหน้า",
	"dayPeriods-standAlone-abbr-evening1": "ในตอนเย็น",
	"dayPeriods-standAlone-abbr-evening2": "ค่ำ",
	"dateFormatItem-hm": "h:mm a",
	"dayPeriods-standAlone-wide-midnight": "เที่ยงคืน",
	"field-year-narrow": "ปี",
	"dateFormatItem-mmss": "mm:ss",
	"dayPeriods-standAlone-abbr-noon": "เที่ยง",
	"field-tue-short-relative+0": "อังคารนี้",
	"dayPeriods-standAlone-narrow-midnight": "เที่ยงคืน",
	"field-tue-short-relative+1": "อังคารหน้า",
	"field-tue-narrow-relative+0": "อังคารนี้",
	"field-tue-narrow-relative+1": "อังคารหน้า",
	"dateTimeFormat-full": "{1} {0}",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-EBhm": "E h:mm B",
	"dateFormatItem-H": "HH",
	"field-wed-relative+0": "พุธนี้",
	"field-wed-relative+1": "พุธหน้า",
	"dateFormatItem-M": "L",
	"field-wed-short-relative+0": "พุธนี้",
	"field-fri-short-relative+0": "ศุกร์นี้",
	"field-wed-short-relative+1": "พุธหน้า",
	"field-fri-short-relative+1": "ศุกร์หน้า",
	"field-weekOfMonth-short": "สัปดาห์ของเดือน",
	"field-quarter-short-relative+-1": "ไตรมาสที่แล้ว",
	"field-year-short-relative+-1": "ปีที่แล้ว",
	"dateFormatItem-yMMMEEEEd": "EEEEที่ d MMM y",
	"dateFormatItem-Bhm": "h:mm B",
	"dayPeriods-format-wide-night1": "กลางคืน",
	"dateTimeFormat-medium": "{1} {0}",
	"field-quarter-narrow-relative+-1": "ไตรมาสที่แล้ว",
	"dateFormatItem-d": "d",
	"dayPeriods-format-abbr-pm": "หลังเที่ยง",
	"dateFormatItem-h": "h a",
	"quarters-standAlone-wide": [
		"ไตรมาส 1",
		"ไตรมาส 2",
		"ไตรมาส 3",
		"ไตรมาส 4"
	],
	"field-weekOfMonth-narrow": "สัปดาห์ของเดือน",
	"dateFormatItem-y": "y",
	"field-minute-relative+0": "นาทีนี้",
	"field-year-short-relative+0": "ปีนี้",
	"dateFormatItem-EBhms": "E h:mm:ss B",
	"field-year-short-relative+1": "ปีหน้า",
	"field-weekday": "วันของสัปดาห์",
	"dayPeriods-format-narrow-pm": "p",
	"field-tue-narrow-relative+-1": "อังคารที่แล้ว",
	"dateFormatItem-yMEd": "E d/M/y",
	"dayPeriods-standAlone-wide-night1": "กลางคืน",
	"field-year-narrow-relative+-1": "ปีที่แล้ว",
	"field-sat-relative+-1": "เสาร์ที่แล้ว",
	"dayPeriods-format-abbr-midnight": "เที่ยงคืน",
	"dayPeriods-format-narrow-morning1": "เช้า",
	"dayPeriods-format-wide-morning1": "ในตอนเช้า",
	"dayPeriods-standAlone-abbr-midnight": "เที่ยงคืน",
	"dayPeriods-standAlone-narrow-pm": "หลังเที่ยง",
	"dayPeriods-standAlone-wide-morning1": "ในตอนเช้า",
	"field-mon-narrow-relative+0": "จันทร์นี้",
	"field-mon-narrow-relative+1": "จันทร์หน้า",
	"field-second": "วินาที",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"field-year-relative+-1": "ปีที่แล้ว",
	"field-weekdayOfMonth-short": "วันของเดือน",
	"dateFormat-short": "d/M/yy",
	"eraNames": [
		"ปีก่อนคริสตกาล",
		"คริสต์ศักราช"
	],
	"field-second-short": "วิ",
	"field-thu-short-relative+-1": "พฤหัสที่แล้ว",
	"field-zone": "เขตเวลา",
	"field-dayperiod-narrow": "ช่วงวัน",
	"field-sun-short-relative+-1": "วันอาทิตย์ที่แล้ว",
	"dayPeriods-standAlone-narrow-morning1": "เช้า",
	"eraAbbr": [
		"ก่อน ค.ศ.",
		"ค.ศ."
	],
	"field-week-short": "สัปดาห์",
	"dayPeriods-standAlone-abbr-am": "ก่อนเที่ยง",
	"dayPeriods-standAlone-wide-pm": "หลังเที่ยง",
	"dateFormatItem-ms": "mm:ss",
	"field-day-relative+0": "วันนี้",
	"field-day-relative+1": "พรุ่งนี้",
	"field-day-relative+2": "มะรืนนี้",
	"field-day-short-relative+0": "วันนี้",
	"field-dayOfYear-short": "วันของปี",
	"field-day-short-relative+1": "พรุ่งนี้",
	"dateFormat-long": "d MMMM G y",
	"field-day-short-relative+2": "มะรืนนี้",
	"field-sun-narrow-relative+-1": "วันอาทิตย์ที่แล้ว",
	"dayPeriods-format-wide-noon": "เที่ยง",
	"field-second-relative+0": "ขณะนี้",
	"field-quarter-relative+-1": "ไตรมาสที่แล้ว",
	"dayPeriods-format-narrow-night1": "กลางคืน",
	"quarters-format-abbr": [
		"ไตรมาส 1",
		"ไตรมาส 2",
		"ไตรมาส 3",
		"ไตรมาส 4"
	],
	"dayPeriods-standAlone-wide-noon": "เที่ยง",
	"dayPeriods-standAlone-narrow-night1": "กลางคืน",
	"field-week-relative+-1": "สัปดาห์ที่แล้ว",
	"dayPeriods-format-abbr-morning1": "ในตอนเช้า",
	"field-month-relative+-1": "เดือนที่แล้ว",
	"months-format-narrow": [
		"ม.ค.",
		"ก.พ.",
		"มี.ค.",
		"เม.ย.",
		"พ.ค.",
		"มิ.ย.",
		"ก.ค.",
		"ส.ค.",
		"ก.ย.",
		"ต.ค.",
		"พ.ย.",
		"ธ.ค."
	],
	"field-year": "ปี",
	"field-era": "สมัย",
	"dayPeriods-standAlone-abbr-morning1": "ในตอนเช้า",
	"days-standAlone-short": [
		"อา.",
		"จ.",
		"อ.",
		"พ.",
		"พฤ.",
		"ศ.",
		"ส."
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"dateFormatItem-yQQQQ": "QQQQ G y",
	"field-day-short-relative+-1": "เมื่อวาน",
	"field-day-short-relative+-2": "เมื่อวานซืน",
	"dateFormatItem-GyMMM": "MMM G y",
	"timeFormat-full": "H นาฬิกา mm นาที ss วินาที zzzz",
	"dateFormatItem-Bhms": "h:mm:ss B",
	"field-hour": "ชั่วโมง",
	"field-dayOfYear-narrow": "วันของปี",
	"field-quarter": "ไตรมาส",
	"field-month-narrow-relative+0": "เดือนนี้",
	"field-month-narrow-relative+1": "เดือนหน้า",
	"field-day": "วัน",
	"dateFormatItem-yMMMMEEEEd": "EEEEที่ d MMMM G y",
	"field-mon-relative+-1": "จันทร์ที่แล้ว",
	"field-dayOfYear": "วันของปี",
	"dateFormat-medium": "d MMM y",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-GyMMMd": "d MMM G y",
	"dateFormatItem-MEd": "E d/M",
	"field-tue-short-relative+-1": "อังคารที่แล้ว",
	"field-year-short": "ปี",
	"field-month-short": "เดือน",
	"dateFormatItem-MMMEd": "E d MMM",
	"dayPeriods-format-wide-afternoon1": "ในตอนบ่าย",
	"dateFormatItem-MMMd": "d MMM",
	"dayPeriods-format-wide-afternoon2": "บ่าย",
	"dateFormatItem-Bh": "h B",
	"months-format-abbr": [
		"ม.ค.",
		"ก.พ.",
		"มี.ค.",
		"เม.ย.",
		"พ.ค.",
		"มิ.ย.",
		"ก.ค.",
		"ส.ค.",
		"ก.ย.",
		"ต.ค.",
		"พ.ย.",
		"ธ.ค."
	],
	"dayPeriods-format-abbr-am": "ก่อนเที่ยง",
	"field-sat-relative+0": "เสาร์นี้",
	"dayPeriods-format-wide-pm": "หลังเที่ยง",
	"field-sat-relative+1": "เสาร์หน้า",
	"days-standAlone-abbr": [
		"อา.",
		"จ.",
		"อ.",
		"พ.",
		"พฤ.",
		"ศ.",
		"ส."
	],
	"field-zone-short": "โซน",
	"field-week-short-relative+0": "สัปดาห์นี้",
	"dateFormatItem-yMMMMd": "d MMMM G y",
	"field-week-short-relative+1": "สัปดาห์หน้า",
	"dayPeriods-standAlone-wide-afternoon1": "ในตอนบ่าย",
	"dayPeriods-standAlone-wide-afternoon2": "บ่าย",
	"field-fri-short-relative+-1": "ศุกร์ที่แล้ว",
	"field-month-narrow": "เดือน",
	"dayPeriods-format-narrow-am": "a",
	"field-month-narrow-relative+-1": "เดือนที่แล้ว",
	"days-format-abbr": [
		"อา.",
		"จ.",
		"อ.",
		"พ.",
		"พฤ.",
		"ศ.",
		"ส."
	],
	"field-weekday-short": "วันของสัปดาห์",
	"field-day-narrow-relative+-1": "เมื่อวาน",
	"field-day-narrow-relative+-2": "เมื่อวานซืน",
	"field-quarter-short": "ไตรมาส",
	"days-format-short": [
		"อา.",
		"จ.",
		"อ.",
		"พ.",
		"พฤ.",
		"ศ.",
		"ส."
	],
	"months-standAlone-narrow": [
		"ม.ค.",
		"ก.พ.",
		"มี.ค.",
		"เม.ย.",
		"พ.ค.",
		"มิ.ย.",
		"ก.ค.",
		"ส.ค.",
		"ก.ย.",
		"ต.ค.",
		"พ.ย.",
		"ธ.ค."
	],
	"days-format-narrow": [
		"อา",
		"จ",
		"อ",
		"พ",
		"พฤ",
		"ศ",
		"ส"
	],
	"dateFormatItem-EHm": "E HH:mm น.",
	"field-quarter-narrow": "ไตรมาส",
	"field-mon-short-relative+0": "จันทร์นี้",
	"field-mon-short-relative+1": "จันทร์หน้า",
	"field-dayperiod-short": "ช่วงวัน",
	"dayPeriods-standAlone-narrow-am": "ก่อนเที่ยง",
	"field-week-narrow-relative+-1": "สัปดาห์ที่แล้ว",
	"field-thu-relative+-1": "พฤหัสที่แล้ว",
	"field-fri-narrow-relative+-1": "ศุกร์ที่แล้ว",
	"field-mon-short-relative+-1": "จันทร์ที่แล้ว",
	"timeFormat-medium": "HH:mm:ss",
	"field-quarter-short-relative+0": "ไตรมาสนี้",
	"field-quarter-short-relative+1": "ไตรมาสหน้า",
	"dateFormatItem-Ed": "E d",
	"field-wed-relative+-1": "พุธที่แล้ว",
	"field-weekOfMonth": "สัปดาห์ของเดือน",
	"field-weekdayOfMonth-narrow": "วันของเดือน",
	"dayPeriods-standAlone-wide-am": "ก่อนเที่ยง",
	"dateFormatItem-yQQQ": "QQQ y",
	"field-fri-relative+-1": "ศุกร์ที่แล้ว",
	"field-minute": "นาที",
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-format-wide": [
		"ไตรมาส 1",
		"ไตรมาส 2",
		"ไตรมาส 3",
		"ไตรมาส 4"
	],
	"field-day-short": "วัน",
	"field-dayperiod": "ช่วงวัน",
	"field-hour-short": "ชม.",
	"months-standAlone-abbr": [
		"ม.ค.",
		"ก.พ.",
		"มี.ค.",
		"เม.ย.",
		"พ.ค.",
		"มิ.ย.",
		"ก.ค.",
		"ส.ค.",
		"ก.ย.",
		"ต.ค.",
		"พ.ย.",
		"ธ.ค."
	],
	"field-month-relative+0": "เดือนนี้",
	"field-second-narrow": "วิ",
	"field-month-relative+1": "เดือนหน้า",
	"dateFormat-full": "EEEEที่ d MMMM G y",
	"field-era-narrow": "สมัย",
	"field-sat-short-relative+-1": "เสาร์ที่แล้ว",
	"dayPeriods-format-narrow-noon": "เที่ยง",
	"field-week-short-relative+-1": "สัปดาห์ที่แล้ว",
	"dateFormatItem-yMMMMEd": "E d MMMM G y",
	"dateTimeFormat-long": "{1} {0}",
	"dateFormatItem-yM": "M/y",
	"field-sun-relative+-1": "วันอาทิตย์ที่แล้ว",
	"field-wed-short-relative+-1": "พุธที่แล้ว",
	"field-weekdayOfMonth": "วันของเดือน",
	"dateFormatItem-MMMEEEEd": "EEEEที่ d MMM",
	"field-quarter-narrow-relative+0": "ไตรมาสนี้",
	"dateFormatItem-GyMMMEd": "E d MMM G y",
	"field-quarter-narrow-relative+1": "ไตรมาสหน้า",
	"field-sat-short-relative+0": "เสาร์นี้",
	"field-sat-short-relative+1": "เสาร์หน้า",
	"field-hour-narrow": "ชม.",
	"field-year-narrow-relative+0": "ปีนี้",
	"field-year-narrow-relative+1": "ปีหน้า",
	"dateFormatItem-Gy": "G y",
	"field-zone-narrow": "เขตเวลา",
	"dayPeriods-standAlone-narrow-noon": "เที่ยง",
	"field-tue-relative+-1": "อังคารที่แล้ว",
	"dateFormatItem-yw": "สัปดาห์ที่ w ของปี Y",
	"dateFormatItem-Hm": "HH:mm น.",
	"field-week-relative+0": "สัปดาห์นี้",
	"field-week-relative+1": "สัปดาห์หน้า",
	"dateFormatItem-MMMMEEEEd": "EEEEที่ d MMMM",
	"dateFormatItem-MMM": "LLL",
	"field-sun-relative+0": "วันอาทิตย์นี้",
	"field-sun-relative+1": "วันอาทิตย์หน้า",
	"field-sat-narrow-relative+-1": "เสาร์ที่แล้ว",
	"quarters-standAlone-abbr": [
		"ไตรมาส 1",
		"ไตรมาส 2",
		"ไตรมาส 3",
		"ไตรมาส 4"
	],
	"dateFormatItem-MMMMW": "สัปดาห์ที่ W ของเดือนMMMM",
	"field-month-short-relative+-1": "เดือนที่แล้ว",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"dateFormatItem-MMMMd": "d MMMM",
	"field-week": "สัปดาห์",
	"field-day-narrow": "วัน"
}
//end v1.x content
);