
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is
 * provided to support globbing requires, custom xtypes, and other
 * metadata-driven class system features
 */

Ext.Boot.loadSyncBasePrefix([
  "packages/sencha-core/.sencha/package/Boot.js",
  "packages/sencha-core/src/Ext.js",
  "packages/sencha-core/src/lang/Error.js",
  "packages/sencha-core/src/lang/Array.js",
  "packages/sencha-core/src/lang/Assert.js",
  "packages/sencha-core/src/lang/String.js",
  "packages/sencha-core/src/lang/Date.js",
  "packages/sencha-core/src/lang/Function.js",
  "packages/sencha-core/src/lang/Number.js",
  "packages/sencha-core/src/lang/Object.js",
  "packages/sencha-core/src/Util.js",
  "packages/sencha-core/src/util/Version.js",
  "packages/sencha-core/src/class/Config.js",
  "packages/sencha-core/src/class/Configurator.js",
  "packages/sencha-core/src/class/Base.js",
  "packages/sencha-core/src/class/Class.js",
  "packages/sencha-core/src/class/Inventory.js",
  "packages/sencha-core/src/class/ClassManager.js",
  "packages/sencha-core/src/env/Browser.js",
  "packages/sencha-core/src/env/OS.js",
  "packages/sencha-core/src/env/Feature.js",
  "packages/sencha-core/src/env/Ready.js",
  "packages/sencha-core/src/class/Loader.js",
  "packages/sencha-core/src/dom/Helper.js",
  "packages/sencha-core/src/util/Format.js",
  "packages/sencha-core/src/Template.js"
]);

