define(
//begin v1.x content
{
	"dateFormatItem-yMMMM": "y年M月",
	"field-thu-narrow-relative+0": "今週の木曜",
	"field-thu-narrow-relative+1": "来週の木曜",
	"field-sun-narrow-relative+0": "今週の日曜",
	"field-sun-narrow-relative+1": "来週の日曜",
	"months-format-wide": [
		"1月",
		"2月",
		"3月",
		"4月",
		"5月",
		"6月",
		"7月",
		"8月",
		"9月",
		"10月",
		"11月",
		"12月"
	],
	"dayPeriods-standAlone-abbr-pm": "午後",
	"dateFormatItem-Hms": "H:mm:ss",
	"field-fri-narrow-relative+0": "今週の金曜",
	"field-fri-narrow-relative+1": "来週の金曜",
	"eraNarrow": [
		"BC",
		"AD"
	],
	"dateFormatItem-Hmv": "H:mm v",
	"dateFormatItem-hmsv": "aK:mm:ss v",
	"dateFormatItem-yMMMd": "y年M月d日",
	"dayPeriods-format-abbr-night1": "夜",
	"dayPeriods-format-abbr-night2": "夜中",
	"dayPeriods-format-narrow-evening1": "夕方",
	"days-standAlone-narrow": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"days-standAlone-wide": [
		"日曜日",
		"月曜日",
		"火曜日",
		"水曜日",
		"木曜日",
		"金曜日",
		"土曜日"
	],
	"dayPeriods-format-abbr-afternoon1": "昼",
	"dayPeriods-format-wide-evening1": "夕方",
	"dateFormatItem-Ehm": "aK:mm (E)",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-wed-narrow-relative+-1": "先週の水曜",
	"dayPeriods-standAlone-wide-evening1": "夕方",
	"days-format-wide": [
		"日曜日",
		"月曜日",
		"火曜日",
		"水曜日",
		"木曜日",
		"金曜日",
		"土曜日"
	],
	"dateFormatItem-yMM": "y/MM",
	"field-month-short-relative+0": "今月",
	"field-month-short-relative+1": "来月",
	"dateFormatItem-Ehms": "aK:mm:ss (E)",
	"dayPeriods-standAlone-narrow-evening1": "夕方",
	"dayPeriods-standAlone-abbr-afternoon1": "昼",
	"field-thu-relative+0": "今週の木曜日",
	"dayPeriods-standAlone-abbr-night1": "夜",
	"field-thu-relative+1": "来週の木曜日",
	"dayPeriods-standAlone-abbr-night2": "夜中",
	"dayPeriods-format-wide-am": "午前",
	"field-fri-relative+0": "今週の金曜日",
	"field-fri-relative+1": "来週の金曜日",
	"dateFormatItem-yMd": "y/M/d",
	"field-thu-narrow-relative+-1": "先週の木曜",
	"field-quarter-relative+0": "今四半期",
	"field-quarter-relative+1": "翌四半期",
	"field-sun-short-relative+0": "今週の日曜",
	"timeFormat-short": "H:mm",
	"field-sun-short-relative+1": "来週の日曜",
	"dateFormatItem-hms": "aK:mm:ss",
	"dayPeriods-format-narrow-afternoon1": "昼",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-Hmsv": "H:mm:ss v",
	"dateFormatItem-hmv": "aK:mm v",
	"field-week-narrow": "週",
	"dateFormatItem-GyMMMEEEEd": "Gy年M月d日EEEE",
	"field-hour-relative+0": "1 時間以内",
	"field-day-relative+-1": "昨日",
	"field-day-relative+-2": "一昨日",
	"field-mon-narrow-relative+-1": "先週の月曜",
	"field-minute-narrow": "分",
	"field-thu-short-relative+0": "今週の木曜",
	"field-mon-relative+0": "今週の月曜日",
	"field-thu-short-relative+1": "来週の木曜",
	"field-mon-relative+1": "来週の月曜日",
	"field-day-narrow-relative+0": "今日",
	"field-era-short": "時代",
	"field-day-narrow-relative+1": "明日",
	"field-sat-narrow-relative+0": "今週の土曜",
	"field-day-narrow-relative+2": "明後日",
	"timeFormat-long": "H:mm:ss z",
	"field-sat-narrow-relative+1": "来週の土曜",
	"field-week-narrow-relative+0": "今週",
	"field-week-narrow-relative+1": "来週",
	"field-wed-narrow-relative+0": "今週の水曜",
	"field-wed-narrow-relative+1": "来週の水曜",
	"field-month": "月",
	"months-standAlone-wide": [
		"1月",
		"2月",
		"3月",
		"4月",
		"5月",
		"6月",
		"7月",
		"8月",
		"9月",
		"10月",
		"11月",
		"12月"
	],
	"field-weekday-narrow": "曜日",
	"dayPeriods-standAlone-narrow-afternoon1": "昼",
	"field-year-relative+0": "今年",
	"field-year-relative+1": "来年",
	"dayPeriods-format-abbr-evening1": "夕方",
	"dayPeriods-format-abbr-noon": "正午",
	"dayPeriods-format-narrow-midnight": "真夜中",
	"dayPeriods-format-wide-midnight": "真夜中",
	"field-tue-relative+0": "今週の火曜日",
	"field-tue-relative+1": "来週の火曜日",
	"dayPeriods-standAlone-abbr-evening1": "夕方",
	"dateFormatItem-hm": "aK:mm",
	"dayPeriods-standAlone-wide-midnight": "真夜中",
	"field-year-narrow": "年",
	"dayPeriods-standAlone-abbr-noon": "正午",
	"field-tue-short-relative+0": "今週の火曜",
	"dayPeriods-standAlone-narrow-midnight": "真夜中",
	"field-tue-short-relative+1": "来週の火曜",
	"field-tue-narrow-relative+0": "今週の火曜",
	"field-tue-narrow-relative+1": "来週の火曜",
	"dateTimeFormat-full": "{1} {0}",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-EBhm": "BK:mm (E)",
	"dateFormatItem-H": "H時",
	"field-wed-relative+0": "今週の水曜日",
	"field-wed-relative+1": "来週の水曜日",
	"dateFormatItem-M": "M月",
	"field-wed-short-relative+0": "今週の水曜",
	"field-fri-short-relative+0": "今週の金曜",
	"field-wed-short-relative+1": "来週の水曜",
	"field-fri-short-relative+1": "来週の金曜",
	"field-weekOfMonth-short": "月の週番号",
	"field-quarter-short-relative+-1": "前四半期",
	"field-year-short-relative+-1": "昨年",
	"dateFormatItem-yMMMEEEEd": "y年M月d日EEEE",
	"dateFormatItem-Bhm": "BK:mm",
	"dayPeriods-format-wide-night1": "夜",
	"dayPeriods-format-wide-night2": "夜中",
	"dateTimeFormat-medium": "{1} {0}",
	"field-quarter-narrow-relative+-1": "前四半期",
	"dateFormatItem-d": "d日",
	"dayPeriods-format-abbr-pm": "午後",
	"dateFormatItem-h": "aK時",
	"quarters-standAlone-wide": [
		"第1四半期",
		"第2四半期",
		"第3四半期",
		"第4四半期"
	],
	"field-weekOfMonth-narrow": "月の週番号",
	"dateFormatItem-y": "y年",
	"field-minute-relative+0": "1 分以内",
	"field-year-short-relative+0": "今年",
	"dateFormatItem-EBhms": "BK:mm:ss (E)",
	"field-year-short-relative+1": "来年",
	"field-weekday": "曜日",
	"dayPeriods-format-narrow-pm": "午後",
	"field-tue-narrow-relative+-1": "先週の火曜",
	"dateFormatItem-yMEd": "y/M/d(E)",
	"dayPeriods-standAlone-wide-night1": "夜",
	"dayPeriods-standAlone-wide-night2": "夜中",
	"field-year-narrow-relative+-1": "昨年",
	"field-sat-relative+-1": "先週の土曜日",
	"dayPeriods-format-abbr-midnight": "真夜中",
	"dayPeriods-format-narrow-morning1": "朝",
	"dateFormatItem-EEEEd": "d日EEEE",
	"dayPeriods-format-wide-morning1": "朝",
	"dayPeriods-standAlone-abbr-midnight": "真夜中",
	"dayPeriods-standAlone-narrow-pm": "午後",
	"dayPeriods-standAlone-wide-morning1": "朝",
	"field-mon-narrow-relative+0": "今週の月曜",
	"field-mon-narrow-relative+1": "来週の月曜",
	"field-second": "秒",
	"dateFormatItem-yMMMEd": "y年M月d日(E)",
	"field-year-relative+-1": "昨年",
	"field-weekdayOfMonth-short": "月の曜日番号",
	"dateFormat-short": "y/MM/dd",
	"eraNames": [
		"紀元前",
		"西暦"
	],
	"field-second-short": "秒",
	"field-thu-short-relative+-1": "先週の木曜",
	"field-zone": "タイムゾーン",
	"field-dayperiod-narrow": "午前/午後",
	"field-sun-short-relative+-1": "先週の日曜",
	"dayPeriods-standAlone-narrow-morning1": "朝",
	"eraAbbr": [
		"紀元前",
		"西暦"
	],
	"field-week-short": "週",
	"dayPeriods-standAlone-abbr-am": "午前",
	"dayPeriods-standAlone-wide-pm": "午後",
	"dateFormatItem-ms": "mm:ss",
	"field-day-relative+0": "今日",
	"field-day-relative+1": "明日",
	"field-day-relative+2": "明後日",
	"field-day-short-relative+0": "今日",
	"field-dayOfYear-short": "年の通日",
	"field-day-short-relative+1": "明日",
	"dateFormat-long": "y年M月d日",
	"field-day-short-relative+2": "明後日",
	"field-sun-narrow-relative+-1": "先週の日曜",
	"dayPeriods-format-wide-noon": "正午",
	"field-second-relative+0": "今",
	"field-quarter-relative+-1": "前四半期",
	"dayPeriods-format-narrow-night1": "夜",
	"dayPeriods-format-narrow-night2": "夜中",
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"dayPeriods-standAlone-wide-noon": "正午",
	"dayPeriods-standAlone-narrow-night1": "夜",
	"dayPeriods-standAlone-narrow-night2": "夜中",
	"field-week-relative+-1": "先週",
	"dayPeriods-format-abbr-morning1": "朝",
	"field-month-relative+-1": "先月",
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"field-year": "年",
	"field-era": "時代",
	"dayPeriods-standAlone-abbr-morning1": "朝",
	"days-standAlone-short": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"dateFormatItem-yQQQQ": "y年QQQQ",
	"field-day-short-relative+-1": "昨日",
	"field-day-short-relative+-2": "一昨日",
	"dateFormatItem-GyMMM": "Gy年M月",
	"timeFormat-full": "H時mm分ss秒 zzzz",
	"dateFormatItem-yMEEEEd": "y/M/dEEEE",
	"dateFormatItem-Bhms": "BK:mm:ss",
	"field-hour": "時",
	"field-dayOfYear-narrow": "通日",
	"field-quarter": "四半期",
	"field-month-narrow-relative+0": "今月",
	"field-month-narrow-relative+1": "来月",
	"field-day": "日",
	"field-mon-relative+-1": "先週の月曜日",
	"field-dayOfYear": "年の通日",
	"dateFormat-medium": "y/MM/dd",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-yMMM": "y年M月",
	"dateFormatItem-GyMMMd": "Gy年M月d日",
	"dateFormatItem-MEd": "M/d(E)",
	"field-tue-short-relative+-1": "先週の火曜",
	"field-year-short": "年",
	"field-month-short": "月",
	"dateFormatItem-MMMEd": "M月d日(E)",
	"dayPeriods-format-wide-afternoon1": "昼",
	"dateFormatItem-MMMd": "M月d日",
	"dateFormatItem-Bh": "BK時",
	"months-format-abbr": [
		"1月",
		"2月",
		"3月",
		"4月",
		"5月",
		"6月",
		"7月",
		"8月",
		"9月",
		"10月",
		"11月",
		"12月"
	],
	"dayPeriods-format-abbr-am": "午前",
	"field-sat-relative+0": "今週の土曜日",
	"field-sat-relative+1": "来週の土曜日",
	"dayPeriods-format-wide-pm": "午後",
	"days-standAlone-abbr": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"field-zone-short": "タイムゾーン",
	"field-week-short-relative+0": "今週",
	"field-week-short-relative+1": "来週",
	"dayPeriods-standAlone-wide-afternoon1": "昼",
	"field-fri-short-relative+-1": "先週の金曜",
	"field-month-narrow": "月",
	"dayPeriods-format-narrow-am": "午前",
	"field-month-narrow-relative+-1": "先月",
	"days-format-abbr": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"field-weekday-short": "曜日",
	"field-day-narrow-relative+-1": "昨日",
	"field-day-narrow-relative+-2": "一昨日",
	"field-quarter-short": "四半期",
	"days-format-short": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"days-format-narrow": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"dateFormatItem-EHm": "H:mm (E)",
	"field-quarter-narrow": "四半期",
	"field-mon-short-relative+0": "今週の月曜",
	"field-mon-short-relative+1": "来週の月曜",
	"field-dayperiod-short": "午前/午後",
	"dayPeriods-standAlone-narrow-am": "午前",
	"field-week-narrow-relative+-1": "先週",
	"field-thu-relative+-1": "先週の木曜日",
	"field-fri-narrow-relative+-1": "先週の金曜",
	"field-mon-short-relative+-1": "先週の月曜",
	"timeFormat-medium": "H:mm:ss",
	"field-quarter-short-relative+0": "今四半期",
	"field-quarter-short-relative+1": "翌四半期",
	"dateFormatItem-Ed": "d日(E)",
	"field-wed-relative+-1": "先週の水曜日",
	"field-weekOfMonth": "月の週番号",
	"field-weekdayOfMonth-narrow": "月の曜日番号",
	"dayPeriods-standAlone-wide-am": "午前",
	"dateFormatItem-yQQQ": "y/QQQ",
	"field-fri-relative+-1": "先週の金曜日",
	"field-minute": "分",
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-format-wide": [
		"第1四半期",
		"第2四半期",
		"第3四半期",
		"第4四半期"
	],
	"dateFormatItem-MEEEEd": "M/dEEEE",
	"field-day-short": "日",
	"field-dayperiod": "午前/午後",
	"field-hour-short": "時",
	"months-standAlone-abbr": [
		"1月",
		"2月",
		"3月",
		"4月",
		"5月",
		"6月",
		"7月",
		"8月",
		"9月",
		"10月",
		"11月",
		"12月"
	],
	"field-month-relative+0": "今月",
	"field-second-narrow": "秒",
	"field-month-relative+1": "来月",
	"dateFormat-full": "y年M月d日EEEE",
	"field-era-narrow": "時代",
	"field-sat-short-relative+-1": "先週の土曜",
	"dayPeriods-format-narrow-noon": "正午",
	"field-week-short-relative+-1": "先週",
	"dateTimeFormat-long": "{1} {0}",
	"dateFormatItem-yM": "y/M",
	"field-sun-relative+-1": "先週の日曜日",
	"field-wed-short-relative+-1": "先週の水曜",
	"field-weekdayOfMonth": "月の曜日番号",
	"dateFormatItem-MMMEEEEd": "M月d日EEEE",
	"field-quarter-narrow-relative+0": "今四半期",
	"dateFormatItem-GyMMMEd": "Gy年M月d日(E)",
	"field-quarter-narrow-relative+1": "翌四半期",
	"field-sat-short-relative+0": "今週の土曜",
	"field-sat-short-relative+1": "来週の土曜",
	"field-hour-narrow": "時",
	"field-year-narrow-relative+0": "今年",
	"field-year-narrow-relative+1": "来年",
	"dateFormatItem-Gy": "Gy年",
	"field-zone-narrow": "タイムゾーン",
	"dayPeriods-standAlone-narrow-noon": "正午",
	"field-tue-relative+-1": "先週の火曜日",
	"field-minute-short": "分",
	"dateFormatItem-yw": "Y年第w週",
	"dateFormatItem-Hm": "H:mm",
	"field-week-relative+0": "今週",
	"field-week-relative+1": "来週",
	"dateFormatItem-MMM": "M月",
	"field-sun-relative+0": "今週の日曜日",
	"field-sun-relative+1": "来週の日曜日",
	"field-sat-narrow-relative+-1": "先週の土曜",
	"quarters-standAlone-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"dateFormatItem-MMMMW": "M月第W週",
	"field-month-short-relative+-1": "先月",
	"dateFormatItem-EHms": "H:mm:ss (E)",
	"dateFormatItem-MMMMd": "M月d日",
	"field-week": "週",
	"field-day-narrow": "日"
}
//end v1.x content
);