import Despot from "../util/Despot";
import Container from "./container";
import { VideomailClientOptions } from "../types/options";
declare class Buttons extends Despot {
    private container;
    private buttonsElement?;
    private recordButton?;
    private pauseButton?;
    private resumeButton?;
    private previewButton?;
    private recordAgainButton?;
    private submitButton?;
    private audioOnRadioPair;
    private audioOffRadioPair;
    private built;
    constructor(container: Container, options: VideomailClientOptions);
    private replaceClickHandler;
    private makeRadioButtonPair;
    private makeButton;
    private buildButtons;
    private onFormReady;
    private onGoingBack;
    private onReplayShown;
    private onUserMediaReady;
    private onResetting;
    private onPreview;
    enableSubmit(): void;
    adjustButtonsForPause(): void;
    private onFirstFrameSent;
    private onRecording;
    private onResuming;
    private onStopping;
    private onCountdown;
    private onSubmitting;
    private onSubmitted;
    private onInvalid;
    private onValid;
    private onHidden;
    private onEnablingAudio;
    private onDisablingAudio;
    private recordAgain;
    private onStartingOver;
    private submit;
    private record;
    private initEvents;
    reset(): void;
    isRecordAgainButtonEnabled(): boolean;
    isReady(): boolean;
    isRecordButtonEnabled(): boolean;
    setSubmitButton(newSubmitButton: any): void;
    getSubmitButton(): HTMLButtonElement | undefined;
    build(): void;
    unload(): void;
    hide(deep?: boolean): void;
    show(): void;
    isCountingDown(): boolean | undefined;
}
export default Buttons;
