/*
 Highcharts JS v11.0.1 (2023-05-08)

 Dependency wheel module

 (c) 2010-2021 Torstein Honsi

 License: www.highcharts.com/license
*/
'use strict';(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/dependency-wheel",["highcharts","highcharts/modules/sankey"],function(d){b(d);b.Highcharts=d;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function d(b,f,d,h){b.hasOwnProperty(f)||(b[f]=h.apply(null,d),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:f,
module:b[f]}})))}b=b?b._modules:{};d(b,"Series/DependencyWheel/DependencyWheelPoint.js",[b["Core/Series/SeriesRegistry.js"],b["Core/Utilities.js"]],function(b,d){var f=this&&this.__extends||function(){var b=function(e,a){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var e in a)Object.prototype.hasOwnProperty.call(a,e)&&(b[e]=a[e])};return b(e,a)};return function(e,a){function d(){this.constructor=e}if("function"!==typeof a&&null!==a)throw new TypeError("Class extends value "+
String(a)+" is not a constructor or null");b(e,a);e.prototype=null===a?Object.create(a):(d.prototype=a.prototype,new d)}}(),h=d.wrap;return function(b){function e(){var a=null!==b&&b.apply(this,arguments)||this;a.angle=void 0;a.fromNode=void 0;a.index=void 0;a.linksFrom=void 0;a.linksTo=void 0;a.options=void 0;a.series=void 0;a.shapeArgs=void 0;a.toNode=void 0;return a}f(e,b);e.prototype.getDataLabelPath=function(b){var a=this,e=this.series.chart.renderer,d=this.shapeArgs,f=0>this.angle||this.angle>
Math.PI,m=d.start||0,p=d.end||0;this.dataLabelPath?(this.dataLabelPath=this.dataLabelPath.destroy(),delete this.dataLabelPath):h(b,"destroy",function(d){a.dataLabelPath&&(a.dataLabelPath=a.dataLabelPath.destroy());return d.call(b)});return this.dataLabelPath=e.arc({open:!0,longArc:Math.abs(Math.abs(m)-Math.abs(p))<Math.PI?0:1}).attr({x:d.x,y:d.y,r:d.r+(this.dataLabel.options.distance||0),start:f?m:p,end:f?p:m,clockwise:+f}).add(e.defs)};e.prototype.isValid=function(){return!0};return e}(b.seriesTypes.sankey.prototype.pointClass)});
d(b,"Series/DependencyWheel/DependencyWheelSeriesDefaults.js",[],function(){"";return{center:[null,null],curveFactor:.6,startAngle:0,dataLabels:{textPath:{enabled:!1,attributes:{dy:5}}}}});d(b,"Series/DependencyWheel/DependencyWheelSeries.js",[b["Core/Animation/AnimationUtilities.js"],b["Series/DependencyWheel/DependencyWheelPoint.js"],b["Series/DependencyWheel/DependencyWheelSeriesDefaults.js"],b["Core/Globals.js"],b["Series/Sankey/SankeyColumnComposition.js"],b["Core/Series/SeriesRegistry.js"],
b["Core/Utilities.js"]],function(b,d,q,h,r,e,a){var f=this&&this.__extends||function(){var b=function(a,c){b=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&(b[c]=a[c])};return b(a,c)};return function(a,c){function d(){this.constructor=a}if("function"!==typeof c&&null!==c)throw new TypeError("Class extends value "+String(c)+" is not a constructor or null");b(a,c);a.prototype=null===c?Object.create(c):
(d.prototype=c.prototype,new d)}}(),t=b.animObject,u=h.deg2rad;h=e.seriesTypes;b=h.pie;var k=h.sankey;h=a.extend;var m=a.merge;a=function(b){function a(){var a=null!==b&&b.apply(this,arguments)||this;a.data=void 0;a.options=void 0;a.nodeColumns=void 0;a.nodes=void 0;a.points=void 0;return a}f(a,b);a.prototype.animate=function(a){if(!a){var b=t(this.options.animation).duration/2/this.nodes.length;this.nodes.forEach(function(a,d){var c=a.graphic;c&&(c.attr({opacity:0}),setTimeout(function(){a.graphic&&
a.graphic.animate({opacity:1},{duration:b})},b*d))},this);this.points.forEach(function(a){var b=a.graphic;!a.isNode&&b&&b.attr({opacity:0}).animate({opacity:1},this.options.animation)},this)}};a.prototype.createNode=function(a){var b=k.prototype.createNode.call(this,a);b.getSum=function(){return b.linksFrom.concat(b.linksTo).reduce(function(b,a){return b+a.weight},0)};b.offset=function(a){function d(a){return a.fromNode===b?a.toNode:a.fromNode}var c=0,e,g=b.linksFrom.concat(b.linksTo);g.sort(function(a,
b){return d(a).index-d(b).index});for(e=0;e<g.length;e++)if(d(g[e]).index>b.index){g=g.slice(0,e).reverse().concat(g.slice(e).reverse());var f=!0;break}f||g.reverse();for(e=0;e<g.length;e++){if(g[e]===a)return c;c+=g[e].weight}};return b};a.prototype.createNodeColumns=function(){var a=[r.compose([],this)];this.nodes.forEach(function(b){b.column=0;a[0].push(b)});return a};a.prototype.getNodePadding=function(){return this.options.nodePadding/Math.PI};a.prototype.translate=function(){var a=this.options,
b=2*Math.PI/(this.chart.plotHeight+this.getNodePadding()),d=this.getCenter(),e=(a.startAngle-90)*u,f=a.borderRadius,h="object"===typeof f?f.radius:f;k.prototype.translate.call(this);this.nodeColumns[0].forEach(function(c){if(c.sum){var f=c.shapeArgs,g=d[0],m=d[1],k=d[2]/2,l=k-a.nodeWidth,n=e+b*(f.y||0);f=e+b*((f.y||0)+(f.height||0));c.angle=n+(f-n)/2;c.shapeType="arc";c.shapeArgs={x:g,y:m,r:k,innerR:l,start:n,end:f,borderRadius:h};c.dlBox={x:g+Math.cos((n+f)/2)*(k+l)/2,y:m+Math.sin((n+f)/2)*(k+l)/
2,width:1,height:1};c.linksFrom.forEach(function(d){if(d.linkBase){var f,c=d.linkBase.map(function(c,h){c*=b;var k=Math.cos(e+c)*(l+1),n=Math.sin(e+c)*(l+1),p=a.curveFactor||0;f=Math.abs(d.linkBase[3-h]*b-c);f>Math.PI&&(f=2*Math.PI-f);f*=l;f<l&&(p*=f/l);return{x:g+k,y:m+n,cpX:g+(1-p)*k,cpY:m+(1-p)*n}});d.shapeArgs={d:[["M",c[0].x,c[0].y],["A",l,l,0,0,1,c[1].x,c[1].y],["C",c[1].cpX,c[1].cpY,c[2].cpX,c[2].cpY,c[2].x,c[2].y],["A",l,l,0,0,1,c[3].x,c[3].y],["C",c[3].cpX,c[3].cpY,c[0].cpX,c[0].cpY,c[0].x,
c[0].y]]}}})}})};a.defaultOptions=m(k.defaultOptions,q);return a}(k);h(a.prototype,{orderNodes:!1,getCenter:b.prototype.getCenter});a.prototype.pointClass=d;e.registerSeriesType("dependencywheel",a);return a});d(b,"masters/modules/dependency-wheel.src.js",[],function(){})});
//# sourceMappingURL=dependency-wheel.js.map