/*
 Highstock JS v10.3.1 (2022-10-31)

 Indicator series type for Highcharts Stock

 (c) 2010-2021 Pawel Fus, Sebastian Bochan

 License: www.highcharts.com/license
*/
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("highcharts/indicators/indicators",["highcharts","highcharts/modules/stock"],function(k){a(k);a.Highcharts=k;return a}):a("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(a){function k(a,c,h,k){a.hasOwnProperty(c)||(a[c]=k.apply(null,h),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("HighchartsModuleLoaded",{detail:{path:c,module:a[c]}})))}
a=a?a._modules:{};k(a,"Stock/Indicators/SMA/SMAIndicator.js",[a["Core/Chart/Chart.js"],a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,c,h){var k=this&&this.__extends||function(){var f=function(g,b){f=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,e){b.__proto__=e}||function(b,e){for(var d in e)e.hasOwnProperty(d)&&(b[d]=e[d])};return f(g,b)};return function(g,b){function d(){this.constructor=g}f(g,b);g.prototype=null===b?Object.create(b):(d.prototype=b.prototype,
new d)}}(),r=c.seriesTypes.line,p=h.addEvent,t=h.error,u=h.extend,v=h.isArray,f=h.merge,l=h.pick,m=h.splat;h=function(n){function g(){var b=null!==n&&n.apply(this,arguments)||this;b.data=void 0;b.dataEventsToUnbind=void 0;b.linkedParent=void 0;b.options=void 0;b.points=void 0;return b}k(g,n);g.prototype.destroy=function(){this.dataEventsToUnbind.forEach(function(b){b()});n.prototype.destroy.apply(this,arguments)};g.prototype.getName=function(){var b=this.name,d=[];b||((this.nameComponents||[]).forEach(function(b,
f){d.push(this.options.params[b]+l(this.nameSuffixes[f],""))},this),b=(this.nameBase||this.type.toUpperCase())+(this.nameComponents?" ("+d.join(", ")+")":""));return b};g.prototype.getValues=function(b,d){var e=d.period,f=b.xData;b=b.yData;var g=b.length,a=0,l=0,m=[],n=[],h=[],c=-1;if(!(f.length<e)){for(v(b[0])&&(c=d.index?d.index:0);a<e-1;)l+=0>c?b[a]:b[a][c],a++;for(d=a;d<g;d++){l+=0>c?b[d]:b[d][c];var k=[f[d],l/e];m.push(k);n.push(k[0]);h.push(k[1]);l-=0>c?b[d-a]:b[d-a][c]}return{values:m,xData:n,
yData:h}}};g.prototype.init=function(b,d){var e=this;n.prototype.init.call(e,b,d);d=p(a,"afterLinkSeries",function(){var d=!!e.dataEventsToUnbind.length;if(e.linkedParent)if(d||(e.dataEventsToUnbind.push(p(e.linkedParent,"updatedData",function(){e.recalculateValues()})),e.calculateOn.xAxis&&e.dataEventsToUnbind.push(p(e.linkedParent.xAxis,e.calculateOn.xAxis,function(){e.recalculateValues()}))),"init"===e.calculateOn.chart)e.processedYData||e.recalculateValues();else{if(!d)var f=p(e.chart,e.calculateOn.chart,
function(){e.recalculateValues();f()})}else return t("Series "+e.options.linkedTo+" not found! Check `linkedTo`.",!1,b)},{order:0});e.dataEventsToUnbind=[];e.eventsToUnbind.push(d)};g.prototype.recalculateValues=function(){var b=this.points||[],d=(this.xData||[]).length,e={values:[],xData:[],yData:[]},f=[],a=!0;e=this.linkedParent.options?this.getValues(this.linkedParent,this.options.params)||e:e;if(d&&!this.hasGroupedData&&this.visible&&this.points)if(this.cropped){if(this.xAxis){var g=this.xAxis.min;
var l=this.xAxis.max}d=this.cropData(e.xData,e.yData,g,l);for(g=0;g<d.xData.length;g++)f.push([d.xData[g]].concat(m(d.yData[g])));d=e.xData.indexOf(this.xData[0]);g=e.xData.indexOf(this.xData[this.xData.length-1]);-1===d&&g===e.xData.length-2&&f[0][0]===b[0].x&&f.shift();this.updateData(f)}else e.xData.length!==d-1&&e.xData.length!==d+1&&(a=!1,this.updateData(e.values));a&&(this.xData=e.xData,this.yData=e.yData,this.options.data=e.values);this.calculateOn.xAxis&&this.processedXData&&(delete this.processedXData,
this.isDirty=!0,this.redraw());this.isDirtyData=!1};g.prototype.processData=function(){var b=this.options.compareToMain,d=this.linkedParent;n.prototype.processData.apply(this,arguments);this.dataModify&&d&&d.dataModify&&d.dataModify.compareValue&&b&&(this.dataModify.compareValue=d.dataModify.compareValue)};g.defaultOptions=f(r.defaultOptions,{name:void 0,tooltip:{valueDecimals:4},linkedTo:void 0,compareToMain:!1,params:{index:3,period:14}});return g}(r);u(h.prototype,{calculateOn:{chart:"init"},hasDerivedData:!0,
nameComponents:["period"],nameSuffixes:[],useCommonDataGrouping:!0});c.registerSeriesType("sma",h);"";return h});k(a,"Stock/Indicators/EMA/EMAIndicator.js",[a["Core/Series/SeriesRegistry.js"],a["Core/Utilities.js"]],function(a,c){var h=this&&this.__extends||function(){var a=function(c,f){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,f){a.__proto__=f}||function(a,f){for(var l in f)f.hasOwnProperty(l)&&(a[l]=f[l])};return a(c,f)};return function(c,f){function l(){this.constructor=
c}a(c,f);c.prototype=null===f?Object.create(f):(l.prototype=f.prototype,new l)}}(),k=a.seriesTypes.sma,r=c.correctFloat,p=c.isArray,t=c.merge;c=function(a){function c(){var f=null!==a&&a.apply(this,arguments)||this;f.data=void 0;f.options=void 0;f.points=void 0;return f}h(c,a);c.prototype.accumulatePeriodPoints=function(a,c,m){for(var f=0,g=0,b;g<a;)b=0>c?m[g]:m[g][c],f+=b,g++;return f};c.prototype.calculateEma=function(a,c,m,h,g,b,d){a=a[m-1];c=0>b?c[m-1]:c[m-1][b];h="undefined"===typeof g?d:r(c*
h+g*(1-h));return[a,h]};c.prototype.getValues=function(a,c){var f=c.period,h=a.xData,g=(a=a.yData)?a.length:0,b=2/(f+1),d=[],e=[],k=[],l=-1;if(!(g<f)){p(a[0])&&(l=c.index?c.index:0);c=this.accumulatePeriodPoints(f,l,a);for(c/=f;f<g+1;f++){var q=this.calculateEma(h,a,f,b,q,l,c);d.push(q);e.push(q[0]);k.push(q[1]);q=q[1]}return{values:d,xData:e,yData:k}}};c.defaultOptions=t(k.defaultOptions,{params:{index:3,period:9}});return c}(k);a.registerSeriesType("ema",c);"";return c});k(a,"masters/indicators/indicators.src.js",
[],function(){})});
//# sourceMappingURL=indicators.js.map