define(
//begin v1.x content
{
	"field-quarter-short-relative+0": "ова тромесечје",
	"field-quarter-short-relative+1": "следното тромесечје",
	"field-tue-relative+-1": "минатиот вторник",
	"field-year": "година",
	"dateFormatItem-Hm": "HH:mm",
	"field-wed-relative+0": "оваа среда",
	"field-wed-relative+1": "следната среда",
	"dateFormatItem-ms": "mm:ss",
	"field-minute": "минута",
	"field-month-narrow-relative+-1": "минатиот месец",
	"field-tue-narrow-relative+0": "овој вто.",
	"field-tue-narrow-relative+1": "следниот вто.",
	"field-day-short-relative+-1": "вчера",
	"field-thu-short-relative+0": "овој чет.",
	"dateTimeFormat-short": "{1} {0}",
	"field-day-relative+0": "денес",
	"field-day-short-relative+-2": "завчера",
	"field-thu-short-relative+1": "следниот чет.",
	"field-day-relative+1": "утре",
	"field-week-narrow-relative+0": "оваа седмица",
	"field-day-relative+2": "задутре",
	"field-week-narrow-relative+1": "следната седмица",
	"dateFormatItem-EBhms": "E h:mm:ss B",
	"field-wed-narrow-relative+-1": "минатата сре.",
	"field-year-narrow": "год.",
	"field-era-short": "ера",
	"field-year-narrow-relative+0": "оваа год.",
	"field-tue-relative+0": "овој вторник",
	"field-year-narrow-relative+1": "следната год.",
	"field-tue-relative+1": "следниот вторник",
	"field-weekdayOfMonth": "ден од месецот",
	"field-second-short": "сек.",
	"dateFormatItem-MMMd": "dd MMM",
	"field-weekdayOfMonth-narrow": "ден од мес.",
	"field-week-relative+0": "оваа седмица",
	"field-month-relative+0": "овој месец",
	"field-week-relative+1": "следната седмица",
	"field-month-relative+1": "следниот месец",
	"field-sun-narrow-relative+0": "оваа нед.",
	"field-mon-short-relative+0": "овој пон.",
	"field-sun-narrow-relative+1": "следната нед.",
	"field-mon-short-relative+1": "следниот пон.",
	"field-second-relative+0": "сега",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"field-weekOfMonth": "седмица од месецот",
	"field-month-short": "мес.",
	"dateFormatItem-GyMMMEd": "E, dd MMM y 'г'. G",
	"dateFormatItem-yyyyMd": "dd.M.y G",
	"field-day": "ден",
	"field-dayOfYear-short": "ден од год.",
	"field-year-relative+-1": "минатата година",
	"field-sat-short-relative+-1": "минатата саб.",
	"field-hour-relative+0": "часов",
	"dateFormatItem-yyyyMEd": "E, dd.M.y G",
	"field-wed-relative+-1": "минатата среда",
	"dateTimeFormat-medium": "{1} {0}",
	"field-sat-narrow-relative+-1": "минатата саб.",
	"field-second": "секунда",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"dateFormat-long": "dd MMMM y 'г'. G",
	"dateFormatItem-GyMMMd": "dd MMM y 'г'. G",
	"field-quarter": "тромесечје",
	"field-week-short": "сед.",
	"field-day-narrow-relative+0": "денес",
	"field-day-narrow-relative+1": "утре",
	"field-day-narrow-relative+2": "задутре",
	"field-tue-short-relative+0": "овој вто.",
	"field-tue-short-relative+1": "следниот вто.",
	"field-month-short-relative+-1": "минатиот месец",
	"field-mon-relative+-1": "минатиот понеделник",
	"dateFormatItem-GyMMM": "MMM y 'г'. G",
	"field-month": "месец",
	"field-day-narrow": "ден",
	"dateFormatItem-MMM": "LLL",
	"field-minute-short": "мин.",
	"field-dayperiod": "претпладне/попладне",
	"field-sat-short-relative+0": "оваа саб.",
	"field-sat-short-relative+1": "следната саб.",
	"dateFormat-medium": "dd.M.y G",
	"dateFormatItem-yyyyMMMM": "MMMM y 'г'. G",
	"dateFormatItem-yyyyM": "M.y G",
	"field-second-narrow": "сек.",
	"field-mon-relative+0": "овој понеделник",
	"field-mon-relative+1": "следниот понеделник",
	"field-day-narrow-relative+-1": "вчера",
	"field-year-short": "год.",
	"field-day-narrow-relative+-2": "завчера",
	"field-quarter-relative+-1": "последното тромесечје",
	"dateFormatItem-yyyyMMMd": "dd MMM y 'г'. G",
	"field-dayperiod-narrow": "претпладне/попладне",
	"field-week-narrow-relative+-1": "минатата седмица",
	"field-dayOfYear": "ден од годината",
	"field-sat-relative+-1": "минатата сабота",
	"dateTimeFormat-long": "{1} {0}",
	"dateFormatItem-Md": "dd.M",
	"field-hour": "час",
	"dateFormat-full": "EEEE, dd MMMM y 'г'. G",
	"field-month-relative+-1": "минатиот месец",
	"dateFormatItem-Hms": "HH:mm:ss",
	"field-quarter-short": "тромес.",
	"field-sat-narrow-relative+0": "оваа саб.",
	"field-fri-relative+0": "овој петок",
	"field-sat-narrow-relative+1": "следната саб.",
	"field-fri-relative+1": "следниот петок",
	"dateFormatItem-EBhm": "E h:mm B",
	"field-month-narrow-relative+0": "овој месец",
	"field-month-narrow-relative+1": "следниот месец",
	"field-sun-short-relative+0": "оваа нед.",
	"field-sun-short-relative+1": "следната нед.",
	"field-week-relative+-1": "минатата седмица",
	"field-quarter-short-relative+-1": "последното тромесечје",
	"dateFormatItem-Ehm": "E h:mm a",
	"field-quarter-relative+0": "ова тромесечје",
	"field-minute-relative+0": "оваа минута",
	"field-quarter-relative+1": "следното тромесечје",
	"field-wed-short-relative+-1": "минатата сре.",
	"dateFormat-short": "dd.M.y GGGGG",
	"dateFormatItem-Bh": "h B",
	"field-year-narrow-relative+-1": "минатата год.",
	"field-thu-short-relative+-1": "минатиот чет.",
	"dateFormatItem-yyyyMMMEd": "E, dd MMM y 'г'. G",
	"field-mon-narrow-relative+-1": "минатиот пон.",
	"dateFormatItem-MMMMd": "dd MMMM",
	"field-thu-narrow-relative+-1": "минатиот чет.",
	"dateFormatItem-E": "E",
	"dateFormatItem-H": "HH",
	"field-weekOfMonth-short": "седмица од месецот",
	"field-tue-narrow-relative+-1": "минатиот вто.",
	"dateFormatItem-yyyy": "y 'г'. G",
	"dateFormatItem-M": "L",
	"field-wed-short-relative+0": "оваа сре.",
	"field-wed-short-relative+1": "следната сре.",
	"field-sun-relative+-1": "минатата недела",
	"dateFormatItem-MMMMEd": "E, dd MMMM",
	"dateTimeFormat-full": "{1} {0}",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-d": "d",
	"field-weekday": "ден од неделата",
	"field-day-short-relative+0": "денес",
	"field-quarter-narrow-relative+0": "ова тромесечје",
	"field-day-short-relative+1": "утре",
	"field-sat-relative+0": "оваа сабота",
	"field-quarter-narrow-relative+1": "следното тромесечје",
	"dateFormatItem-h": "h a",
	"field-day-short-relative+2": "задутре",
	"field-sat-relative+1": "следната сабота",
	"field-week-short-relative+0": "оваа седмица",
	"field-week-short-relative+1": "следната седмица",
	"field-dayOfYear-narrow": "ден од год.",
	"field-month-short-relative+0": "овој месец",
	"field-month-short-relative+1": "следниот месец",
	"field-weekdayOfMonth-short": "ден од мес.",
	"dateFormatItem-MEd": "E, dd.M",
	"field-zone-narrow": "зона",
	"dateFormatItem-y": "y 'г'. G",
	"field-thu-narrow-relative+0": "овој чет.",
	"field-sun-narrow-relative+-1": "минатата нед.",
	"field-mon-short-relative+-1": "минатиот пон.",
	"field-thu-narrow-relative+1": "следниот чет.",
	"field-thu-relative+0": "овој четврток",
	"field-thu-relative+1": "следниот четврток",
	"dateFormatItem-hms": "h:mm:ss a",
	"field-fri-short-relative+-1": "минатиот пет.",
	"field-thu-relative+-1": "минатиот четврток",
	"field-week": "седмица",
	"dateFormatItem-Ed": "d E",
	"field-wed-narrow-relative+0": "оваа сре.",
	"field-wed-narrow-relative+1": "следната сре.",
	"field-quarter-narrow-relative+-1": "последното тромесечје",
	"field-year-short-relative+0": "оваа год.",
	"dateFormatItem-yyyyMMM": "MMM y 'г'. G",
	"field-dayperiod-short": "претпладне/попладне",
	"field-year-short-relative+1": "следната год.",
	"field-fri-short-relative+0": "овој пет.",
	"field-fri-short-relative+1": "следниот пет.",
	"field-week-short-relative+-1": "минатата седмица",
	"dateFormatItem-yyyyQQQQ": "QQQ y G",
	"field-hour-short": "ч.",
	"field-zone-short": "зона",
	"field-month-narrow": "мес.",
	"field-hour-narrow": "ч.",
	"field-fri-narrow-relative+-1": "минатиот пет.",
	"field-year-relative+0": "оваа година",
	"field-year-relative+1": "следната година",
	"field-era-narrow": "ера",
	"field-fri-relative+-1": "минатиот петок",
	"dateFormatItem-Bhms": "h:mm:ss B",
	"field-tue-short-relative+-1": "минатиот вто.",
	"field-minute-narrow": "мин.",
	"field-mon-narrow-relative+0": "овој пон.",
	"dateFormatItem-EHm": "E HH:mm",
	"field-mon-narrow-relative+1": "следниот пон.",
	"field-year-short-relative+-1": "минатата год.",
	"field-zone": "временска зона",
	"dateFormatItem-MMMEd": "E, dd MMM",
	"field-weekOfMonth-narrow": "седмица од месецот",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"field-weekday-narrow": "ден во неделата",
	"field-quarter-narrow": "тромес.",
	"field-sun-short-relative+-1": "минатата нед.",
	"field-day-relative+-1": "вчера",
	"field-day-relative+-2": "завчера",
	"field-weekday-short": "ден во неделата",
	"dateFormatItem-Bhm": "h:mm B",
	"field-sun-relative+0": "оваа недела",
	"field-sun-relative+1": "следната недела",
	"dateFormatItem-Gy": "y 'г'. G",
	"field-day-short": "ден",
	"field-week-narrow": "сед.",
	"field-era": "ера",
	"field-fri-narrow-relative+0": "овој пет.",
	"field-fri-narrow-relative+1": "следниот пет."
}
//end v1.x content
);