name: sync

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    concurrency: sync
    runs-on: ubuntu-latest

    steps:
     - name: clone
       run: |
         git clone \
           --depth 1  \
           --filter=blob:none \
           --sparse \
           https://${{ secrets.ROBOCDNJS_TOKEN }}@github.com/cdnjs/cdnjs.git
     - name: sync
       run: |
         wget https://github.com/cdnjs/tools/releases/download/ce87c098c9dc2dce6b3f49c77adf4f29b60eb5366/git-sync
         chmod +x ./git-sync
         cd cdnjs
         git config user.name robocdnjs
         git config user.email cdnjs-github@cloudflare.com
         ../git-sync ./last-sync cdnjs-outgoing-prod
         
     - name: push
       run: |
         cd cdnjs
         git push https://robocdnjs:${{ secrets.ROBOCDNJS_TOKEN }}@github.com/cdnjs/cdnjs.git
